version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgis/postgis:13-3.1
    env_file:
      - .env
    volumes:
      - postgres_datavol:/var/lib/postgresql/data

  redis:
      image: redis:latest
      ports:
        - "6379:6379"
volumes:
  postgres_datavol:
  pgadmin_data:
