name: Django CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis:13-3.1
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends gdal-bin libgdal-dev 
          rm -rf /var/lib/apt/lists/*
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Database to Start
        run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - name: Run Migrations
        run: python manage.py migrate

      - name: Run Tests
        run: python manage.py test

      - name: Clean Up Database Container
        run: docker-compose down
